#!/bin/ash
# a helper script to get reg value
# put this file in /usr/bin

regidx=$1

if [ -z $regidx ]; then
	echo "usage: $0 <reg index>"
	exit
fi

echo $regidx > /sys/kernel/debug/ieee80211/phy0/ath9k/regidx
regval=$(cat /sys/kernel/debug/ieee80211/phy0/ath9k/regval)
echo $regval

if [ $regidx = "0x9e1c" ]; then
	CCA_THRESHOLD_raw=$((($regval & 0x7f000) >> 12))
	CCA_THRESHOLD=$(($CCA_THRESHOLD_raw | ~0x7f))
	MINCCA_PWR_raw=$((($regval & 0x1ff00000) >> 20))
	MINCCA_PWR=$(($MINCCA_PWR_raw | ~0x1ff))
	echo "CCA_THRESHOLD: $CCA_THRESHOLD"
	echo "MINCCA_PWR: $MINCCA_PWR"
fi
