#!/bin/sh
# a helper script to set reg value
# put this file in /usr/bin

regidx=$1
regval=$2
field=$2
val=$3

if [ -z $regidx ] || [ -z $regval ]; then
	echo "usage: $0 <reg index> <value>"
	exit
fi

echo $regidx > /sys/kernel/debug/ieee80211/phy0/ath9k/regidx
case $regidx in
	"0x9e1c")	#AR_PHY_CCA_0, baseboard CCA control
		if [ -z $val ]; then
			echo "usage: $0 0x9e1c <maxCCA/minCCA> <val>"
			exit
		fi
		ori_val=$(cat /sys/kernel/debug/ieee80211/phy0/ath9k/regval)
		case $field in
			"maxCCA")
				new_val=$((($ori_val & ~0x7f000) | (($val & 0x7f) << 12)))
				echo $new_val > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
				;;
			"minCCA")
				new_val=$((($ori_val & ~0x1ff00000) | (($val & 0x1ff) << 20)))
				echo $new_val > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
				;;
			*)
				echo "usage: $0 0x9e1c <maxCCA/minCCA> <val>"
				exit
		esac
		;;
	"0x801c")	#AR_USEC, baseband RX/TX latency control
		if [ -z $val ]; then
			echo "usage: $0 0x801c <tx_lat/rx_lat> <val>"
			exit
		fi
		ori_val=$(cat /sys/kernel/debug/ieee80211/phy0/ath9k/regval)
		case $field in
			"tx_lat")
				new_val=$((($ori_val & ~0x7fc000) | (($val & 0x1ff) << 14)))
				echo $new_val > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
				;;
			"rx_lat")
				new_val=$((($ori_val & ~0x1f800000) | (($val & 0x3f) << 23)))
				echo $new_val > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
				;;
			*)
				echo "usage: $0 0x801c <tx_lat/rx_lat> <val>"
				exit
		esac
		;;
	*)
		echo $regval > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
esac
rget $regidx
