#!/bin/ash
# a helper script to set reg value
# put this file in /usr/bin

regidx=$1
regval=$2

if [ -z $regidx ] || [ -z $regval ]; then
	echo "usage: $0 <reg index> <value>"
	exit
fi

echo $regidx > /sys/kernel/debug/ieee80211/phy0/ath9k/regidx
echo $regval > /sys/kernel/debug/ieee80211/phy0/ath9k/regval
cat /sys/kernel/debug/ieee80211/phy0/ath9k/regval
